export type VerificationStatus = 'verified' | 'pending' | 'needs-review';
export type PublicationType = 'Journal article' | 'Conference paper' | 'Book chapter' | 'Thesis';
export interface Researcher { id: string; name: string; role: string; department: string; interests: string[]; domains: string[]; publicationCount: number; citationCount: number; avatar: string; externalProfiles: { label: string; url: string }[]; collaborators: string[]; }
export interface Supervisor { id: string; name: string; department: string; interests: string[]; domains: string[]; supervisedPublications: number; studentResearchers: number; citationCount: number; externalProfiles: { label: string; url: string }[]; }
export interface Department { id: string; name: string; code: string; description: string; publicationCount: number; researcherCount: number; supervisorCount: number; domains: string[]; }
export interface ResearchDomain { id: string; name: string; description: string; publicationCount: number; researchers: number; supervisors: number; departments: string[]; centers: string[]; }
export interface ResearchCenter { id: string; name: string; description: string; domains: string[]; publicationCount: number; researchers: number; supervisors: number; }
export interface Publication { id: string; title: string; abstract: string; authors: string[]; supervisors: string[]; department: string; domains: string[]; center: string; type: PublicationType; venue: string; year: number; date: string; DOI: string; citationCount: number; views: number; downloads: number; verificationStatus: VerificationStatus; openAccess: boolean; url: string; }
export interface Submission extends Publication { submittedBy: string; submittedAt: string; }

export const departments: Department[] = [
  { id: 'computing', name: 'Computing & Mathematics', code: 'CM', description: 'Computational inquiry, mathematical modeling, and the systems that shape our world.', publicationCount: 184, researcherCount: 31, supervisorCount: 14, domains: ['ai', 'data', 'security'] },
  { id: 'business', name: 'Business & Economics', code: 'BE', description: 'Evidence-led perspectives on markets, organizations, and responsible enterprise.', publicationCount: 137, researcherCount: 26, supervisorCount: 11, domains: ['enterprise', 'policy', 'sustainability'] },
  { id: 'health', name: 'Health Sciences', code: 'HS', description: 'Translational health research centered on prevention, community, and human wellbeing.', publicationCount: 122, researcherCount: 28, supervisorCount: 13, domains: ['health', 'community', 'data'] },
  { id: 'education', name: 'Education & Human Development', code: 'ED', description: 'Learning, development, and the social conditions that help people flourish.', publicationCount: 96, researcherCount: 22, supervisorCount: 9, domains: ['education', 'community', 'policy'] },
  { id: 'environment', name: 'Environmental Studies', code: 'ES', description: 'Place-based research for resilient landscapes, communities, and climate futures.', publicationCount: 88, researcherCount: 19, supervisorCount: 8, domains: ['climate', 'sustainability', 'community'] },
  { id: 'arts', name: 'Arts & Communication', code: 'AC', description: 'Critical, creative, and cultural research across media, language, and public life.', publicationCount: 61, researcherCount: 17, supervisorCount: 7, domains: ['culture', 'communication', 'education'] },
];
export const domains: ResearchDomain[] = [
  { id: 'ai', name: 'Artificial Intelligence & Data', description: 'Human-centered computation, trustworthy AI, and the stories hidden in data.', publicationCount: 143, researchers: 38, supervisors: 15, departments: ['Computing & Mathematics', 'Health Sciences'], centers: ['Center for Applied Computing'] },
  { id: 'sustainability', name: 'Sustainability & Climate', description: 'Research for ecological resilience and the communities adapting to a changing climate.', publicationCount: 118, researchers: 29, supervisors: 12, departments: ['Environmental Studies', 'Business & Economics'], centers: ['Sustainability Futures Lab'] },
  { id: 'health', name: 'Health & Wellbeing', description: 'Prevention, access, and evidence that improves health outcomes across communities.', publicationCount: 109, researchers: 34, supervisors: 14, departments: ['Health Sciences', 'Education & Human Development'], centers: ['Community Health Institute'] },
  { id: 'education', name: 'Learning & Human Development', description: 'How people learn, grow, and build more equitable institutions.', publicationCount: 92, researchers: 25, supervisors: 11, departments: ['Education & Human Development', 'Arts & Communication'], centers: ['Learning Futures Studio'] },
  { id: 'enterprise', name: 'Enterprise & Public Policy', description: 'Organizations, policy decisions, and the systems that make economies work.', publicationCount: 86, researchers: 24, supervisors: 10, departments: ['Business & Economics', 'Computing & Mathematics'], centers: ['Civic Systems Observatory'] },
  { id: 'culture', name: 'Culture & Communication', description: 'Meaning-making, media, and public narratives in a connected world.', publicationCount: 63, researchers: 19, supervisors: 8, departments: ['Arts & Communication'], centers: ['Public Culture Lab'] },
];
export const centers: ResearchCenter[] = [
  { id: 'applied-computing', name: 'Center for Applied Computing', description: 'A cross-disciplinary home for useful, responsible computation.', domains: ['Artificial Intelligence & Data', 'Enterprise & Public Policy'], publicationCount: 74, researchers: 17, supervisors: 8 },
  { id: 'sustainability-futures', name: 'Sustainability Futures Lab', description: 'Designing practical pathways for communities living with environmental change.', domains: ['Sustainability & Climate', 'Enterprise & Public Policy'], publicationCount: 62, researchers: 14, supervisors: 6 },
  { id: 'community-health', name: 'Community Health Institute', description: 'Partnering with communities to study and improve everyday health.', domains: ['Health & Wellbeing', 'Learning & Human Development'], publicationCount: 58, researchers: 16, supervisors: 7 },
  { id: 'learning-futures', name: 'Learning Futures Studio', description: 'Researching the learning environments people need next.', domains: ['Learning & Human Development', 'Culture & Communication'], publicationCount: 43, researchers: 12, supervisors: 5 },
  { id: 'civic-systems', name: 'Civic Systems Observatory', description: 'An observatory for the intersection of policy, technology, and public life.', domains: ['Enterprise & Public Policy', 'Artificial Intelligence & Data'], publicationCount: 36, researchers: 9, supervisors: 4 },
  { id: 'public-culture', name: 'Public Culture Lab', description: 'Making visible the cultural practices that connect campus and community.', domains: ['Culture & Communication', 'Learning & Human Development'], publicationCount: 29, researchers: 8, supervisors: 4 },
];
export const researchers: Researcher[] = [
  { id: 'maya-chen', name: 'Dr Maya Chen', role: 'Associate Professor', department: 'Computing & Mathematics', interests: ['Responsible AI', 'Data ethics', 'Public systems'], domains: ['Artificial Intelligence & Data', 'Enterprise & Public Policy'], publicationCount: 27, citationCount: 612, avatar: 'MC', externalProfiles: [{ label: 'ORCID', url: '#' }, { label: 'Google Scholar', url: '#' }], collaborators: ['jonas-wright', 'leila-hassan'] },
  { id: 'jonas-wright', name: 'Prof Jonas Wright', role: 'Professor', department: 'Environmental Studies', interests: ['Climate adaptation', 'Rural resilience', 'Land use'], domains: ['Sustainability & Climate'], publicationCount: 42, citationCount: 982, avatar: 'JW', externalProfiles: [{ label: 'ORCID', url: '#' }, { label: 'ResearchGate', url: '#' }], collaborators: ['maya-chen', 'elinor-park'] },
  { id: 'leila-hassan', name: 'Dr Leila Hassan', role: 'Assistant Professor', department: 'Health Sciences', interests: ['Community health', 'Health access', 'Wellbeing'], domains: ['Health & Wellbeing', 'Artificial Intelligence & Data'], publicationCount: 19, citationCount: 284, avatar: 'LH', externalProfiles: [{ label: 'ORCID', url: '#' }], collaborators: ['maya-chen', 'adrian-cole'] },
  { id: 'elinor-park', name: 'Dr Elinor Park', role: 'Associate Professor', department: 'Education & Human Development', interests: ['Learning design', 'First-generation students', 'Assessment'], domains: ['Learning & Human Development'], publicationCount: 23, citationCount: 438, avatar: 'EP', externalProfiles: [{ label: 'ORCID', url: '#' }, { label: 'Google Scholar', url: '#' }], collaborators: ['jonas-wright'] },
  { id: 'adrian-cole', name: 'Dr Adrian Cole', role: 'Senior Lecturer', department: 'Business & Economics', interests: ['Social enterprise', 'Public value', 'Innovation'], domains: ['Enterprise & Public Policy', 'Sustainability & Climate'], publicationCount: 18, citationCount: 311, avatar: 'AC', externalProfiles: [{ label: 'ORCID', url: '#' }], collaborators: ['leila-hassan'] },
  { id: 'nina-ortiz', name: 'Dr Nina Ortiz', role: 'Lecturer', department: 'Arts & Communication', interests: ['Public media', 'Migration stories', 'Visual culture'], domains: ['Culture & Communication'], publicationCount: 16, citationCount: 197, avatar: 'NO', externalProfiles: [{ label: 'ORCID', url: '#' }], collaborators: ['elinor-park'] },
];
export const supervisors: Supervisor[] = [
  { id: 'maya-chen', name: 'Dr Maya Chen', department: 'Computing & Mathematics', interests: ['Responsible AI', 'Data ethics', 'Public systems'], domains: ['Artificial Intelligence & Data', 'Enterprise & Public Policy'], supervisedPublications: 15, studentResearchers: 8, citationCount: 612, externalProfiles: [{ label: 'ORCID', url: '#' }, { label: 'Google Scholar', url: '#' }] },
  { id: 'jonas-wright', name: 'Prof Jonas Wright', department: 'Environmental Studies', interests: ['Climate adaptation', 'Rural resilience', 'Land use'], domains: ['Sustainability & Climate'], supervisedPublications: 24, studentResearchers: 11, citationCount: 982, externalProfiles: [{ label: 'ORCID', url: '#' }] },
  { id: 'elinor-park', name: 'Dr Elinor Park', department: 'Education & Human Development', interests: ['Learning design', 'Student success', 'Assessment'], domains: ['Learning & Human Development'], supervisedPublications: 17, studentResearchers: 9, citationCount: 438, externalProfiles: [{ label: 'ORCID', url: '#' }] },
];
export const publications: Publication[] = [
  { id: 'pub-001', title: 'Designing accountable AI for public service decisions', abstract: 'This study examines how public institutions can adopt machine learning while preserving due process, explainability, and meaningful human oversight. Through interviews with civic technology teams and a review of deployed systems, we identify four design commitments that make accountability operational rather than aspirational.', authors: ['Dr Maya Chen', 'Dr Adrian Cole'], supervisors: ['Dr Maya Chen'], department: 'Computing & Mathematics', domains: ['Artificial Intelligence & Data', 'Enterprise & Public Policy'], center: 'Center for Applied Computing', type: 'Journal article', venue: 'Journal of Responsible Technology', year: 2024, date: '2024-09-18', DOI: '10.1016/j.jrt.2024.100214', citationCount: 38, views: 1248, downloads: 486, verificationStatus: 'verified', openAccess: true, url: '#' },
  { id: 'pub-002', title: 'Living with water: rural adaptation beyond resilience', abstract: 'A place-based account of how rural communities respond to recurring flood events, challenging the idea that resilience is a fixed community trait.', authors: ['Prof Jonas Wright', 'Dr Nina Ortiz'], supervisors: ['Prof Jonas Wright'], department: 'Environmental Studies', domains: ['Sustainability & Climate', 'Culture & Communication'], center: 'Sustainability Futures Lab', type: 'Journal article', venue: 'Climate & Society', year: 2024, date: '2024-06-02', DOI: '10.1080/14693062.2024.24108', citationCount: 26, views: 962, downloads: 341, verificationStatus: 'verified', openAccess: true, url: '#' },
  { id: 'pub-003', title: 'The hidden curriculum of health access', abstract: 'We explore how navigating health systems creates uneven burdens for first-generation university students and propose a practical framework for more navigable services.', authors: ['Dr Leila Hassan', 'Dr Elinor Park'], supervisors: ['Dr Leila Hassan'], department: 'Health Sciences', domains: ['Health & Wellbeing', 'Learning & Human Development'], center: 'Community Health Institute', type: 'Conference paper', venue: 'International Conference on Community Health', year: 2023, date: '2023-11-11', DOI: '10.1145/3671132.3671208', citationCount: 19, views: 733, downloads: 279, verificationStatus: 'verified', openAccess: false, url: '#' },
  { id: 'pub-004', title: 'Measuring what matters in student belonging', abstract: 'A mixed-methods study of belonging measures and what they reveal about the everyday experience of students entering university.', authors: ['Dr Elinor Park'], supervisors: ['Dr Elinor Park'], department: 'Education & Human Development', domains: ['Learning & Human Development'], center: 'Learning Futures Studio', type: 'Journal article', venue: 'Higher Education Review', year: 2023, date: '2023-04-27', DOI: '10.1080/03075079.2023.2191004', citationCount: 31, views: 1104, downloads: 401, verificationStatus: 'verified', openAccess: true, url: '#' },
  { id: 'pub-005', title: 'Small enterprise, large public value', abstract: 'This chapter follows three local enterprises as they balance economic sustainability with commitments to public value and community ownership.', authors: ['Dr Adrian Cole'], supervisors: ['Dr Adrian Cole'], department: 'Business & Economics', domains: ['Enterprise & Public Policy', 'Sustainability & Climate'], center: 'Civic Systems Observatory', type: 'Book chapter', venue: 'The Public Value Handbook', year: 2022, date: '2022-10-13', DOI: '10.4324/9781003345912-8', citationCount: 14, views: 582, downloads: 218, verificationStatus: 'verified', openAccess: false, url: '#' },
  { id: 'pub-006', title: 'Listening across the archive', abstract: 'A creative practice inquiry into migration stories, public memory, and the responsibilities of cultural institutions.', authors: ['Dr Nina Ortiz'], supervisors: ['Dr Nina Ortiz'], department: 'Arts & Communication', domains: ['Culture & Communication'], center: 'Public Culture Lab', type: 'Journal article', venue: 'Cultural Studies Quarterly', year: 2022, date: '2022-03-09', DOI: '10.1080/09502386.2022.2048134', citationCount: 11, views: 441, downloads: 176, verificationStatus: 'verified', openAccess: true, url: '#' },
];
export const submissions: Submission[] = [
  { ...publications[0], id: 'sub-001', title: 'Community data trusts: a practical primer', verificationStatus: 'pending', submittedBy: 'Samira Bell', submittedAt: '2025-02-07' },
  { ...publications[1], id: 'sub-002', title: 'Wetland restoration and neighborhood health', verificationStatus: 'needs-review', submittedBy: 'Noah Reed', submittedAt: '2025-02-04' },
  { ...publications[2], id: 'sub-003', title: 'Teaching with care: a field guide', verificationStatus: 'verified', submittedBy: 'Priya Shah', submittedAt: '2025-01-28' },
];

export const service = {
  async listPublications() { return publications; },
  async getPublication(id: string) { return publications.find((p) => p.id === id) ?? publications[0]; },
  async listResearchers() { return researchers; },
  async getResearcher(id: string) { return researchers.find((r) => r.id === id) ?? researchers[0]; },
  async listSubmissions() { return submissions; },
};